return {
  { "vimpostor/vim-lumen" },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = function()
      ---@type CatppuccinOptions
      return {
        integrations = { blink_cmp = true },
        -- transparent_background = true,
        highlight_overrides = {
          all = function(colors)
            return {
              NeoTreeDirectoryIcon = { fg = colors.subtext1 },
              NeoTreeDirectoryName = { fg = colors.text },
              NeoTreeFileNameOpened = { bg = colors.subtext0 },
              NeoTreeGitModified = { fg = colors.sky },
              LineNr = {
                fg = colors.subtext1,
              },
              Type = {
                fg = colors.flamingo,
              },
              Keyword = {
                style = {
                  "italic",
                },
              },
              ["@property"] = {
                fg = colors.text,
              },
              ["@variable.java"] = {
                fg = colors.text,
              },
              ["@keyword.return"] = {
                fg = colors.text,
              },
              ["@parameter"] = {
                fg = colors.text,
              },
              ["@variable.member"] = {
                fg = colors.text,
              },
              ["@lsp.typemod.namespace.importDeclaration.java"] = {
                fg = colors.text,
              },
              Function = {
                style = { "italic" },
              },
              NeoTreeCursorLine = {
                fg = colors.blue,
                style = {
                  "bold",
                  "italic",
                },
              },
              NeoTreeIndentMarker = { fg = colors.surface1 },
              CursorLine = { bg = colors.crust },
              FlashLabel = {
                fg = colors.pink,
              },
            }
          end,
        },
        color_overrides = {
          macchiato = {
            rosewater = "#f2d5cf",
            flamingo = "#eebebe",
            pink = "#b48ead",
            mauve = "#9da5d4",
            red = "#d67c83",
            maroon = "#ea999c",
            peach = "#d7917b",
            yellow = "#e1cda5",
            green = "#88c0d0",
            teal = "#81c8be",
            sky = "#99d1db",
            sapphire = "#85c1dc",
            blue = "#a2c0e5",
            lavender = "#babbf1",
            text = "#bdc7d9",
            subtext1 = "#b5bfe2",
            subtext0 = "#a5adce",
            overlay2 = "#949cbb",
            overlay1 = "#838ba7",
            overlay0 = "#737994",
            surface2 = "#626880",
            surface1 = "#51576d",
            surface0 = "#414559",
            base = "#3b4252",
            mantle = "#3b4252",
            crust = "#43485e",
          },
          latte = {
            rosewater = "#43947d",
            flamingo = "#bc6366",
            pink = "#bf5d79",
            mauve = "#5f9759",
            red = "#d06a63",
            maroon = "#449289",
            peach = "#5f8bb5",
            yellow = "#c38027",
            green = "#77863a",
            teal = "#4b9196",
            sky = "#5283a8",
            sapphire = "#528754",
            blue = "#e7804d",
            lavender = "#859347",
            text = "#644d42",
            subtext1 = "#857d66",
            subtext0 = "#918b6f",
            overlay2 = "#ab9188",
            overlay1 = "#b39991",
            overlay0 = "#a2867c",
            surface2 = "#dfd0c6",
            surface1 = "#e6dad3",
            surface0 = "#f1eae3",
            base = "#f1ebe8",
            mantle = "#eee7e3",
            crust = "#f2e4db",
          },
          frappe = {
            rosewater = "#dc9a8d",
            flamingo = "#eebebe",
            pink = "#b98bb1",
            mauve = "#a3a5e2",
            red = "#de717b",
            maroon = "#e9979a",
            peach = "#d9a2b2",
            yellow = "#eba780",
            green = "#7cc2d6",
            teal = "#67b5ab",
            sky = "#99d1db",
            sapphire = "#85c1dc",
            blue = "#cea6d7",
            lavender = "#babbf1",
            text = "#c1c5da",
            subtext1 = "#b5bfe2",
            subtext0 = "#a5adce",
            overlay2 = "#949cbb",
            overlay1 = "#838ba7",
            overlay0 = "#737994",
            surface2 = "#626880",
            surface1 = "#51576d",
            surface0 = "#414559",
            base = "#262934",
            mantle = "#292c39",
            crust = "#43485e",
          },
          mocha = {
            rosewater = "#52ab8f",
            flamingo = "#d5815e",
            pink = "#de859c",
            mauve = "#8abb69",
            red = "#df6b64",
            maroon = "#58b0a2",
            peach = "#da8387",
            yellow = "#e9a25d",
            green = "#48b574",
            teal = "#5fad95",
            sky = "#5fa49f",
            sapphire = "#75b35e",
            blue = "#da9e5a",
            lavender = "#a2a453",
            text = "#cab18a",
            subtext1 = "#aba38b",
            subtext0 = "#9f997f",
            overlay2 = "#9b947f",
            overlay1 = "#837d6d",
            overlay0 = "#6c695e",
            surface2 = "#5c5b52",
            surface1 = "#4d4c4a",
            surface0 = "#3d3b3a",
            base = "#252525",
            mantle = "#262626",
            crust = "#363530",
          },
        },
      }
    end,
  },
  { "ellisonleao/gruvbox.nvim", priority = 1000, config = true },
}
