return {
  { "vimpostor/vim-lumen" },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = function()
      return {
        transparent_background = false,
        highlight_overrides = {
          all = function(colors)
            return {
              NeoTreeDirectoryIcon = { fg = colors.subtext1 },
              NeoTreeDirectoryName = { fg = colors.text },
              NeoTreeFileNameOpened = { bg = colors.subtext0 },
              NeoTreeGitModified = { fg = colors.sky },
              LineNr = {
                fg = colors.subtext1,
              },
              Type = {
                fg = colors.mauve,
                style = { "italic" },
              },
              ["@lsp.mod.typeArgument.java"] = {
                fg = colors.rosewater,
              },
              ["@property"] = {
                fg = colors.text,
              },
              ["@variable.java"] = {
                fg = colors.text,
              },
              ["@variable.parameter"] = {
                fg = colors.text,
              },
              ["@keyword.return"] = {
                fg = colors.text,
              },
              ["@parameter"] = {
                fg = colors.text,
              },
              ["@variable.member"] = {
                fg = colors.text,
              },
              ["@lsp.typemod.namespace.importDeclaration.java"] = {
                fg = colors.text,
              },
              NeoTreeCursorLine = {
                fg = colors.blue,
                style = {
                  "bold",
                  "italic",
                },
              },
              NeoTreeIndentMarker = { fg = colors.surface1 },
              CursorLine = { bg = colors.crust },
            }
          end,
        },
        color_overrides = {
          macchiato = {
            rosewater = "#9dc3a6",
            flamingo = "#d0a0a1",
            pink = "#d79faf",
            mauve = "#a7c080",
            red = "#d17274",
            maroon = "#de8d6c",
            peach = "#86c0bd",
            yellow = "#dc9a6f",
            green = "#81b376",
            teal = "#7fbbb3",
            sky = "#7eb9c3",
            sapphire = "#8abad2",
            blue = "#DBBC7F",
            lavender = "#a7c080",
            text = "#d0be9a",
            subtext1 = "#d2c19e",
            subtext0 = "#baad90",
            overlay2 = "#9c9d83",
            overlay1 = "#87886f",
            overlay0 = "#73735d",
            surface2 = "#4b6162",
            surface1 = "#3a4d4d",
            surface0 = "#283736",
            base = "#262e33",
            mantle = "#293237",
            crust = "#425050",
          },
          latte = {
            rosewater = "#dc8a78",
            flamingo = "#dd7878",
            pink = "#a16d91",
            mauve = "#bf6d87",
            red = "#c96373",
            maroon = "#598898",
            peach = "#ce8068",
            yellow = "#d8935d",
            green = "#5f9678",
            teal = "#569599",
            sky = "#6488a6",
            sapphire = "#4796a6",
            blue = "#816fb3",
            lavender = "#7685c0",
            text = "#615d7e",
            subtext1 = "#5c5f77",
            subtext0 = "#6c6f85",
            overlay2 = "#8d7a88",
            overlay1 = "#9c8a97",
            overlay0 = "#ab9ba7",
            surface2 = "#baacb6",
            surface1 = "#c8bcc5",
            surface0 = "#d7cdd4",
            base = "#fbf3ef",
            mantle = "#faf2ee",
            crust = "#f3e8e3",
          },
          frappe = {
            rosewater = "#dc9a8d",
            flamingo = "#e39d9d",
            pink = "#b98bb1",
            mauve = "#89a5ff",
            red = "#e6848b",
            maroon = "#82c1ed",
            peach = "#df8da1",
            yellow = "#eda085",
            green = "#71c1cf",
            teal = "#67b5ab",
            sky = "#99d1db",
            sapphire = "#85c1dc",
            blue = "#c7b0f7",
            lavender = "#babbf1",
            text = "#bcc4ec",
            subtext1 = "#b5bfe2",
            subtext0 = "#a5adce",
            overlay2 = "#949cbb",
            overlay1 = "#838ba7",
            overlay0 = "#737994",
            surface2 = "#626880",
            surface1 = "#51576d",
            surface0 = "#414559",
            base = "#333744",
            mantle = "#323643",
            crust = "#414662",
          },
          mocha = {
            rosewater = "#b18e3d",
            flamingo = "#dd7878",
            pink = "#7382ba",
            mauve = "#5e7c38",
            red = "#c15852",
            maroon = "#ac5d69",
            peach = "#4a947c",
            yellow = "#e68015",
            green = "#5e9953",
            teal = "#1b888e",
            sky = "#3a94c5",
            sapphire = "#4590a0",
            blue = "#ca8c35",
            lavender = "#6a83e2",
            text = "#627464",
            subtext1 = "#5a6552",
            subtext0 = "#71735f",
            overlay2 = "#81826f",
            overlay1 = "#8f9281",
            overlay0 = "#a5a191",
            surface2 = "#b4b1a2",
            surface1 = "#c4c1b3",
            surface0 = "#d3d0c4",
            base = "#f6f3ee",
            mantle = "#f5f2ec",
            crust = "#e3e0d5",
          },
        },
      }
    end,
  },
}
