return {
  { "vimpostor/vim-lumen" },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = function()
      return {
        integrations = { blink_cmp = true },
        transparent_background = true,
        highlight_overrides = {
          all = function(colors)
            return {
              NeoTreeDirectoryIcon = { fg = colors.subtext1 },
              NeoTreeDirectoryName = { fg = colors.text },
              NeoTreeFileNameOpened = { bg = colors.subtext0 },
              NeoTreeGitModified = { fg = colors.sky },
              LineNr = {
                fg = colors.subtext1,
              },
              Type = {
                fg = colors.flamingo,
              },
              Keyword = {
                style = {
                  "italic",
                },
              },
              ["@property"] = {
                fg = colors.text,
              },
              ["@variable.java"] = {
                fg = colors.text,
              },
              ["@keyword.return"] = {
                fg = colors.text,
              },
              ["@parameter"] = {
                fg = colors.text,
              },
              ["@variable.member"] = {
                fg = colors.text,
              },
              ["@lsp.typemod.namespace.importDeclaration.java"] = {
                fg = colors.text,
              },
              Function = {
                style = { "italic" },
              },
              NeoTreeCursorLine = {
                fg = colors.blue,
                style = {
                  "bold",
                  "italic",
                },
              },
              NeoTreeIndentMarker = { fg = colors.surface1 },
              CursorLine = { bg = colors.crust },
              FlashLabel = {
                fg = colors.pink,
              },
            }
          end,
        },
        color_overrides = {
          macchiato = {
            rosewater = "#7cbea9",
            flamingo = "#d99c95",
            pink = "#cf839a",
            mauve = "#a7c080",
            red = "#d67c83",
            maroon = "#db8989",
            peach = "#77bcc0",
            yellow = "#ec9c6f",
            green = "#83c092",
            teal = "#7fbbb3",
            sky = "#76b2ba",
            sapphire = "#97aeda",
            blue = "#e69875",
            lavender = "#d699b6",
            text = "#c2baa6",
            subtext1 = "#9da996",
            subtext0 = "#93a699",
            overlay2 = "#9da9a0",
            overlay1 = "#859289",
            overlay0 = "#859289",
            surface2 = "#4d5960",
            surface1 = "#5d6b66",
            surface0 = "#4d5960",
            base = "#293136",
            mantle = "#293136",
            crust = "#4d5960",
          },
          latte = {
            rosewater = "#43947d",
            flamingo = "#ca7372",
            pink = "#bd667e",
            mauve = "#c4606b",
            red = "#ca635c",
            maroon = "#886ca7",
            peach = "#5585a3",
            yellow = "#e78d41",
            green = "#3f916e",
            teal = "#bc6481",
            sky = "#4d7ca0",
            sapphire = "#629e64",
            blue = "#4d8799",
            lavender = "#859347",
            text = "#5d5a77",
            subtext1 = "#7d7a95",
            subtext0 = "#8986a5",
            overlay2 = "#c2a9a6",
            overlay1 = "#b59996",
            overlay0 = "#ad8f8c",
            surface2 = "#ded0cd",
            surface1 = "#e5dad9",
            surface0 = "#e9e0dd",
            base = "#fffbf9",
            mantle = "#faf6f2",
            crust = "#ded2ce",
          },
          frappe = {
            rosewater = "#dc9a8d",
            flamingo = "#e39d9d",
            pink = "#b98bb1",
            mauve = "#a7a4f3",
            red = "#e6848b",
            maroon = "#90c0e2",
            peach = "#e7a3b2",
            yellow = "#eaa288",
            green = "#71c1cf",
            teal = "#67b5ab",
            sky = "#99d1db",
            sapphire = "#85c1dc",
            blue = "#d8adec",
            lavender = "#babbf1",
            text = "#bcc4ec",
            subtext1 = "#b5bfe2",
            subtext0 = "#a5adce",
            overlay2 = "#949cbb",
            overlay1 = "#838ba7",
            overlay0 = "#737994",
            surface2 = "#626880",
            surface1 = "#51576d",
            surface0 = "#414559",
            base = "#2e323f",
            mantle = "#323645",
            crust = "#414662",
          },
          mocha = {
            rosewater = "#52ab8f",
            flamingo = "#d5815e",
            pink = "#de859c",
            mauve = "#8abb69",
            red = "#df6b64",
            maroon = "#58b0a2",
            peach = "#da8387",
            yellow = "#e9a25d",
            green = "#48b574",
            teal = "#5fad95",
            sky = "#5fa49f",
            sapphire = "#75b35e",
            blue = "#da9e5a",
            lavender = "#a2a453",
            text = "#cab18a",
            subtext1 = "#aba38b",
            subtext0 = "#9f997f",
            overlay2 = "#9b947f",
            overlay1 = "#837d6d",
            overlay0 = "#6c695e",
            surface2 = "#5c5b52",
            surface1 = "#4d4c4a",
            surface0 = "#3d3b3a",
            base = "#252525",
            mantle = "#262626",
            crust = "#363530",
          },
        },
      }
    end,
  },
}
